# vim:ft=kitty

## name:     Catppuccin Kitty Frappé
## author:   Catppuccin Org | Modded by Luther
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/frappe.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #bfbfbf
background              #1a1a1a
selection_foreground    #1a1a1a
selection_background    #e6cca1

# Cursor colors
cursor                  #e6cca1
cursor_text_color       #1a1a1a

# URL underline color when hovering with mouse
url_color               #e6cca1

# Kitty window border colors
active_border_color     #f5f5f5
inactive_border_color   #d99f82
bell_border_color       #e6cca1

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #6da18a
active_tab_background   #e6cca1
inactive_tab_foreground #bfbfbf
inactive_tab_background #6da18a
tab_bar_background      #6da18a

# Colors for marks (marked text in the terminal)
mark1_foreground #1a1a1a
mark1_background #f5f5f5
mark2_foreground #1a1a1a
mark2_background #ca9ee6
mark3_foreground #1a1a1a
mark3_background #85c1dc

# The 16 terminal colors

# black
color0 #363636
color8 #363636

# red
color1 #bd555f
color9 #bd555f

# green
color2  #86bf8f
color10 #86bf8f

# yellow
color3  #e6cca1
color11 #e6cca1

# blue
color4  #82b5d9
color12 #82b5d9

# magenta
color5  #c98f8f
color13 #c98f8f

# cyan
color6  #a1d5e6
color14 #a1d5e6

# white
color7  #f5f5f5
color15 #f5f5f5

#Shell Function
shell fish

#Tab Bar
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

#Fonts
font_family      Kubasta
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 8.0

#Mouse
mouse_hide_wait 3.0

#Clipboard
map ctrl+c copy_or_interrupt
map cmd+c copy_or_interrupt 🍎

map ctrl+v paste_from_clipboard
map cmd+v paste_from_clipboard 🍎
