[FileDialog]
history=file:///home/luther/Documents/Obsidian/Other Heaven/01 - Software Development/Grimheart/Eden Map, file:///home/luther/Documents/Profession/Game Development/_Assets/Reference/Mood Boards, file:///home/luther/Downloads, file:///home/luther/Pictures/Screenshots/Temp, file:///home/luther/Documents/Archives/Program Settings & Exports/QBitTorrent
lastVisited=file:///home/luther/Downloads
qtVersion=6.10.2
shortcuts=file:///home/luther/Desktop, file:///home/luther/Documents, file:///home/luther/Downloads, file:///home/luther, file:mods
sidebarWidth=122
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xfc\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1 \0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
